version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - api-network
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db
    networks:
      - api-network
    restart: always
networks:
  api-network:
    driver: bridge